server:
  port: 8002
# 路由转发，将/member/...的请求转发了member模块
# 路由转发，将/business/...的请求转发了business模块
spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri:
            http://127.0.0.1:8001
          predicates:
            - Path=/member/**
        - id: business
          uri:
            http://127.0.0.1:8003
          predicates:
            - Path=/business/**
        - id: batch
          uri:
            http://127.0.0.1:8004
          predicates:
            - Path=/batch/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*" # 允许请求来源（老版本叫allowedOrigin）
            allowedHeaders: "*" # 允许携带的头信息
            allowedMethods: "*" # 允许的请求方式
            allowCredentials: true # 是否允许携带cookie
            maxAge: 3600 # 跨域检测的有效期，会发起一个OPTION请求


